
name: Testing CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-and-build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ostad
          MONGO_INITDB_ROOT_PASSWORD: ostad

    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Read hello.txt
        run: |
          echo "Contents of hello.txt:"
          cat hello.txt

      - name: Show success message
        run: echo "✅ Build + Read Success..002 - txt file read"
